### PR TITLE
Split package

### LINKED ISSUE #6: Split package so library-only code doesn't pull in Scribble
It would be helpful to users to have `-lib`, `-doc` packages separated out. I'm willing to do the work if you're willing to merge it.

### PR DESCRIPTION
**Pull request by wilbowma**
Closes #6

### CODE REVIEW

**Comment by wilbowma** [comment]
Ping

**Comment by sorawee** [comment]
@jbclements do you also need to register `-lib` and `-doc` at https://pkgs.racket-lang.org? Currently, installation fails.

**Comment by jbclements** [comment]
Yep, duh. Should be fixed now.

**Comment by sorawee** [comment]
FYI: `memoize-test`'s URL is currently linking to https://github.com/jbclements/memoize.git?path=memoize-doc. I assume you meant to link to memoize-test.

**Comment by jbclements** [comment]
Oh for Heaven's sake. it seems like a miracle that I didn't create some kind of endless loop. What happens if a package depends on itself? I'm guessing that that doesn't cause a problem, based on evidence from this accidental test. Anyhow, should be fixed now. ...

OH! Actually, I think I may have just found a bug in Racket's package system. :) still looking....

**Comment by jbclements** [comment]
Okay, writing this down here so I don't forget.

I updated the package metadata to point to the correct subpath of the repo (memoize-test, rather than memoize-doc), but a `raco pkg update` didn't make any changes or recompile anything. consider the following transcript:

```
hardy:/tmp/memoize (git)-[master]- clements> raco pkg update memoize-test
Resolving "memoize-test" via https://pkgs.racket-lang.org
No updates available
hardy:/tmp/memoize (git)-[master]- clements> raco pkg catalog-show memoize-test
Package name: memoize-test
 Author: clements@racket-lang.org
 Source: https://github.com/jbclements/memoize.git?path=memoize-test#master
 Checksum: c1a772c849b35bc30327036db1abe2574419aca5
 Tags: memoization
 Description: testing code for memoize
 Ring: 2
 Dependencies:
  base
  rackunit-lib
  scribble-lib
  racket-doc
  memoize-lib
hardy:/tmp/memoize (git)-[master]- clements> racket
Welcome to Racket v8.3.0.11 [cs].
> (require memoize/private/tests)
string:1:9: collection not found
  for module path: memoize/private/tests
  collection: "memoize/private"
  in collection directories:
   /Users/clements/Library/Racket/development/collects
   /Users/clements/racket/racket/collects/
   ... [255 additional linked and package directories]
 [,bt for context]
> 
hardy:/tmp/memoize (git)-[master]- clements> 
```

Note that the catalog still shows dependencies on the packages required by memoize-doc, and that requiring `tests.rkt` fails, indicating that the memoize-test package is not updated.

This suggests to me that racket's recompilation-needed checking depends only on the checksum, & not on the repo subpath. Of course, 98% of the time when I find a bug like this, it turns out to be my fault, so I'm checking by creating a new bogus directory in the memoize repo with a file that definitely doesn't compile.

**Pull request merged**
